apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enuygun-app.fullname" . }}
  labels:
    app: {{ include "enuygun-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "enuygun-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "enuygun-app.name" . }}
    spec:
      containers:
        - name: {{ include "enuygun-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 80
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
