replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 200m

nodeSelector:
  cloud.google.com/gke-nodepool: application-pool

tolerations:
  - key: "app-pool"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
